version: "3.8"

services:
  zot:
    image: ghcr.io/project-zot/zot-linux-arm64:v2.1.11
    container_name: zot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./zot-config.json:/etc/zot/config.json:ro
      - ./htpasswd:/etc/zot/htpasswd:ro
      - ./data:/var/lib/registry

networks:
  default:
    external: true
    name: nginx-proxy-network
